RegisterNetEvent("dutySystem:notifyDutyStatus", function(message)
    SetNotificationTextEntry("STRING")
    AddTextComponentString("~b~[Duty System]~s~ " .. message)
    DrawNotification(false, true)
end)
